name: Build
on: [push]

jobs:
  tests:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 8']
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.0'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: make tests
