name: Build
on: [push]

jobs:
  tests:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 8']
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.0.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: make tests
